### ISSUE TITLE
Support for php 7.*

### ISSUE THREAD

**Issue by ehibes** [TheCadien/SuluNewsBundle#16]
Hi, why do you choose to support on php 8 only ? Sulu 2.4 supports php 7.* too. 
Thanks in advance.

**Comment by TheCadien** [comment]
Hi ehibes, I would like to write the bundle cleanly in PHP 8 conventions. I am aware that Sulu itself supports php 7 and I am making a small break here in support. 
However, there is currently no plan to change that, sorry :/
