### ISSUE TITLE
Sulu 2.5 Support

### ISSUE THREAD

**Issue by TheCadien** [TheCadien/SuluNewsBundle#24]

**Comment by manuxi** [comment]
+1

**Comment by TheCadien** [comment]
@manuxi 
We have decided to release the support for the versions 2.4 and 2.5 in time these days so that the bundle can at least be used in newer Sulu versions. 
The features of the versions like the trash bin will be added afterwards. 
So stay tuned

**Comment by FlorianBoe** [comment]
Hi, is there already news for the compatibility release for 2.5?

**Comment by TheCadien** [comment]
Still have a bug at the moment. 
`The controller for URI "/_sulu_preview" is not callable: Controller "sulu_news.controller:indexAction" does neither exist as service nor as class.`

But we are working on it. We hope to be able to report positive progress soon.

**Comment by TheCadien** [comment]
For progress see: https://github.com/TheCadien/SuluNewsBundle/pull/25

**Comment by TheCadien** [comment]
@FlorianBoe , @manuxi , @mavuio , @kleffsche and @akleineb. 
please try to install and ttest the branch `[sulu25](https://github.com/TheCadien/SuluNewsBundle/tree/sulu25)` in your Projects. 
think that them now should be working an we could merge and release that update. 

I am looking forward to your feedback

**Comment by kleffsche** [comment]
The "preview" error is gone. Can you please tell me, how to select the news within a block or as a page property? Or is it only possible to get new news within a view?

Thank you very much for your work.

**Comment by kleffsche** [comment]
> @kleffsche That bundle provides forexample the [smart_content](https://docs.sulu.io/en/2.5/reference/content-types/smart_content.html) component (currently in a heavy basic way)
That you could try. Think that should work for you :)

`smart_content` does not work as expected. All news are always selected. No way to select single news. It would be great if the `news_selection` and the `single_news_selection` would work in future. 

Thank you.

**Comment by TheCadien** [comment]
@kleffsche fix that ticket aber we finshed the 2.5 Update. 
More details than in #28

**Comment by FlorianBoe** [comment]
I have the 2.5 branch in use and have not found any problems so far. Thanks for your great work!

**Comment by FlorianBoe** [comment]
I just noticed that the SEO tab is not working. Text input in all fields leads to an error message in the browser console.
```
Uncaught TypeError: Cannot set properties of undefined (setting 'title')
```
