### ISSUE TITLE
createDimensionContent error 

### ISSUE THREAD

**Issue by kleffsche** [TheCadien/SuluNewsBundle#26]
Hi there, 

first, thank you very much for your work. I’d like to get this bundle to work, but it won't show up in the admin menu bar. 

Perhaps because of the following error

`The return type of method "createDimensionContent" in class "TheCadien\Bundle\SuluNewsBundle\Entity\News" is invalid.`

I'm using  Sulu 2.5 and Symfony 6

**Comment by TheCadien** [comment]
Hey Klaffsche, 

thank you for your Feedback and creating that Issue. 
I think that bug is because your using Sulu 2.5 and Symfony 6. 
I currently working on the Support for that Versions. 
Hope i can release that soon

https://github.com/TheCadien/SuluNewsBundle/pull/25
