### ISSUE TITLE
Type "news_selection" not available

### ISSUE THREAD

**Issue by kleffsche** [TheCadien/SuluNewsBundle#28]
So I managed to install this bundle with Sulu 2.5 and Symfony 6 but when I try to select news (type `news_selection`)on a page, for example in homepage.xml like this:

```
<property name="news" type="news_selection" mandatory="true">
    <params>
        <param name="min" value="1"/>
    </params>
</property>
```

the page won't load anymore. 

When I try to load news in a block:

```
<type name="news">
    <properties>
        <property name="news-select" type="news_selection" mandatory="true">
            <params>
                <param name="min" value="1"/>
            </params>
        </property>
    </properties>
</type>
```

the page loads but I got this error: 

<img width="783" alt="image" src="https://user-images.githubusercontent.com/2162793/200292299-aec13393-3351-4fbb-8b39-cd2d0c7a67bb.png">

**Comment by TheCadien** [comment]
Thanks for reporting, the news_selection will be fixed in the next release with the Sulu 2.5 and Symfony Update again. 
<img width="526" alt="Bildschirm­foto 2022-11-09 um 23 30 02" src="https://user-images.githubusercontent.com/9395097/200956688-934c8d3a-4b48-4104-aa0e-55725b0fb274.png">

**Comment by TheCadien** [comment]
I think it would still make sense to write a Twig extension here so that the news can be landed more easily in the frontend. 
What do you think @kleffsche ? Could you test the usability ?

**Comment by kleffsche** [comment]
That works very well, I just have to figure out how to get the items from the news, or better, from the resolved news (`sulu_resolve_news`), but I guess this twig extension makes it a lot easier.

A small example, how I get the data in a twig view: 

```
{% for newsItem in content.news %}
     {% set news = sulu_resolve_news(newsItem.id) %}
     {% if news.header.id|default %}
         {% set image = sulu_resolve_media(news.header.id, app.request.locale) %}
             <img src="{{ image.thumbnails['2560x550'] }}">
     {% endif %}
{% endfor %}
```

I think that's the right way to do it with data from a `news_selection`, isn't it?

Thank you, again, for your help and this very useful bundle. :+1
