### ISSUE TITLE
Not Showing in Admin

### ISSUE THREAD

**Issue by porl** [TheCadien/SuluNewsBundle#34]
I have installed the bundle following the instructions at https://github.com/TheCadien/SuluNewsBundle and https://github.com/TheCadien/SuluNewsBundle/blob/master/Resources/docs/installation.md however I see no "News" entry in the admin area.

Is there another step I need to do to add this? I've cleared the cache etc. but do not see any evidence the bundle is functioning.

Thanks

**Comment by TheCadien** [comment]
Hello @porl , 

The News Bundle is equipped with its own roles and rights configuration. If you add it to an installation afterwards, the respective role has no rights in the backend (Read, Write, View). 
Please go to the roles menu and set these 3 of your role and reload. Then you should see it. 
But you're right, we should probably include this step in the docs. 
Maybe you would like to open a PR :) ?

**Comment by porl** [comment]
Looks like I just needed to assign the role permissions and then the menu item showed up.

Perhaps this should be added to the installation document?

**Comment by porl** [comment]
For some reason your response didn't show before I posted my reply!

**Comment by porl** [comment]
Pull request:
https://github.com/TheCadien/SuluNewsBundle/pull/35

**Comment by TheCadien** [comment]
Thank you for open the PR :) !
