### ISSUE TITLE
Question about list view 

### ISSUE THREAD

**Issue by danielkeho** [TheCadien/SuluNewsBundle#36]
How list view of news is created with this bundle please

**Comment by TheCadien** [comment]
Hello Daniel 
Could you be more specific with your question ?
Do you mean the list view in the admin backend ? Or a listing of the news in the frontend on the website.

In the case of the admin backend, the list is created as described in the Sulu documentation, see [here](https://docs.sulu.io/en/2.5/book/extend-admin.html?highlight=extend#configure-list-view). 

In case of the frontend please use the Sulu Smart Content Component. There is an extension in the bundle that can be used for the news as well. Take a look [here](https://docs.sulu.io/en/2.5/reference/content-types/smart_content.htmlt).

**Comment by danielkeho** [comment]
Thank you very much  @TheCadien  for your availability and your clear, precise and concise answer. Indeed, I was talking about the frontend. I'm new to sulu and I've already used smart_ontent. But in this case I have no idea how to use the extension or how it looks like. It seems I'm missing something fundamental in the understanding of things.

**Comment by TheCadien** [comment]
@danielkeho ahh ok i see. Could you please move the Question to "Discussions" ? 

Then I pack you there with pleasure an example how to use it purely. Issues are closed and then no one has them more on in view and discussions also indexes Google, so that future people looking for it will find ? That would be very nice of you.

**Comment by danielkeho** [comment]
Well noted  @TheCadien . Thanks.  I will open discussion about it.
